Clone eisop repositories

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -41,21 +41,21 @@ jobs:
       set -ex
       if [ -d /tmp/$USER/plume-scripts ]; \
         then git -C /tmp/$USER/plume-scripts pull -q > /dev/null 2>&1 ; \
-        else mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git ; \
+        else mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/eisop-plume-lib/plume-scripts.git ; \
       fi
     displayName: plume-scripts
   # This creates ../jdk17u .
   # If the depth is too small, the merge will fail.
   - bash: |
       set -ex
-      /tmp/$USER/plume-scripts/git-clone-related typetools jdk17u ../jdk17u -q --depth 99
+      /tmp/$USER/plume-scripts/git-clone-related eisop jdk17u ../jdk17u -q --depth 99
     displayName: clone-related-jdk17u
   - bash: |
       set -ex
       git config --global user.email "you@example.com"
       git config --global user.name "Your Name"
-      eval `/tmp/$USER/plume-scripts/ci-info typetools`
-      cd ../jdk17u && git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH} || (echo "Merge failed; see 'Pull request merge conflicts' at https://github.com/typetools/jdk/blob/master/README" && false)
+      eval `/tmp/$USER/plume-scripts/ci-info eisop`
+      cd ../jdk17u && git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH} || (echo "Merge failed; see 'Pull request merge conflicts' at https://github.com/eisop/jdk/blob/master/README" && false)
     displayName: git merge
   - bash: cd ../jdk17u && export JT_HOME=/usr/share/jtreg && bash ./configure --with-jtreg --disable-warnings-as-errors
     displayName: configure
@@ -81,9 +81,9 @@ jobs:
   steps:
   - checkout: self
     fetchDepth: 25
-  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git
+  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/eisop-plume-lib/plume-scripts.git
     displayName: clone plume-scripts
-  - bash: /tmp/$USER/plume-scripts/git-clone-related typetools checker-framework
+  - bash: /tmp/$USER/plume-scripts/git-clone-related eisop checker-framework
     displayName: clone checker-framework
   - bash: (cd ../checker-framework && checker/bin-devel/test-cftests-all.sh)
     displayName: test-cftests-all.sh
@@ -96,9 +96,9 @@ jobs:
   steps:
   - checkout: self
     fetchDepth: 25
-  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git
+  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/eisop-plume-lib/plume-scripts.git
     displayName: clone plume-scripts
-  - bash: /tmp/$USER/plume-scripts/git-clone-related typetools checker-framework
+  - bash: /tmp/$USER/plume-scripts/git-clone-related eisop checker-framework
     displayName: clone checker-framework
 # test-cftests-all.sh sometimes runs out of memory, but running its component parts in sequence does not.
 #   - bash: (cd ../checker-framework && checker/bin-devel/test-cftests-all.sh)
@@ -128,9 +128,9 @@ jobs:
   steps:
   - checkout: self
     fetchDepth: 25
-  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git
+  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/eisop-plume-lib/plume-scripts.git
     displayName: clone plume-scripts
-  - bash: /tmp/$USER/plume-scripts/git-clone-related typetools checker-framework
+  - bash: /tmp/$USER/plume-scripts/git-clone-related eisop checker-framework
     displayName: clone checker-framework
   - bash: (cd ../checker-framework && checker/bin-devel/test-cftests-all.sh)
     displayName: test-cftests-all.sh
@@ -143,9 +143,9 @@ jobs:
   steps:
   - checkout: self
     fetchDepth: 25
-  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git
+  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/eisop-plume-lib/plume-scripts.git
     displayName: clone plume-scripts
-  - bash: /tmp/$USER/plume-scripts/git-clone-related typetools checker-framework
+  - bash: /tmp/$USER/plume-scripts/git-clone-related eisop checker-framework
     displayName: clone checker-framework
   - bash: (cd ../checker-framework && checker/bin-devel/test-cftests-all.sh)
     displayName: test-cftests-all.sh
@@ -158,9 +158,9 @@ jobs:
   steps:
   - checkout: self
     fetchDepth: 25
-  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git
+  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/eisop-plume-lib/plume-scripts.git
     displayName: clone plume-scripts
-  - bash: /tmp/$USER/plume-scripts/git-clone-related typetools checker-framework
+  - bash: /tmp/$USER/plume-scripts/git-clone-related eisop checker-framework
     displayName: clone checker-framework
   - bash: (cd ../checker-framework && checker/bin-devel/test-daikon.sh)
     displayName: test-daikon.sh
@@ -172,9 +172,9 @@ jobs:
   steps:
   - checkout: self
     fetchDepth: 25
-  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git
+  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/eisop-plume-lib/plume-scripts.git
     displayName: clone plume-scripts
-  - bash: /tmp/$USER/plume-scripts/git-clone-related typetools checker-framework
+  - bash: /tmp/$USER/plume-scripts/git-clone-related eisop checker-framework
     displayName: clone checker-framework
   - bash: (cd ../checker-framework && checker/bin-devel/test-plume-lib.sh)
     displayName: test-plume-lib.sh
